# Generated by Django 4.2.3 on 2023-08-29 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('till_date', models.DateField()),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(max_length=50)),
                ('leave_status', models.PositiveIntegerField(choices=[(0, 'Pending for approval'), (1, 'Approved and update in progress '), (2, 'Approved and updated'), (3, 'Rejected'), (4, 'Approved'), (5, 'Delete approval pending'), (6, 'Deleted and update in progress'), (7, 'Deleted')], default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
