# Generated by Django 4.2.3 on 2023-08-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='leave_status_text',
            field=models.CharField(default='Pending for approval', max_length=60),
        ),
    ]
